name=xpt2046
version=0.0.1
author=Matthias
maintainer=Matthias<matthias.k@outlook.de>
sentence=Rudimentary library for XPT2046 ADC touch driver
paragraph=
category=Display
url=https://github.com/mindgame-84/xpt2046
architectures=*